# Generated by Django 3.2.4 on 2021-09-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('is_paid', models.BooleanField(default=True)),
                ('cod_pagamento', models.CharField(max_length=200)),
            ],
        ),
    ]
