# Generated by Django 3.2.4 on 2021-09-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
        ),
    ]
