# Generated by Django 3.2.4 on 2021-09-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('pedido', '0002_alter_pedido_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='carrinho.carrinho'),
            preserve_default=False,
        ),
    ]
